### ISSUE TITLE
cache.manifest

### ISSUE THREAD

**Issue by bloodyowl** [MoOx/tab#13]

**Comment by kud** [comment]
Could be a good idea!

**Comment by MoOx** [comment]
Nice idea.
I never use that thing.

**Comment by armandabric** [comment]
It in my head, or the online version of the newtab is really fast now ? Pretty usable directly without any local installation. Congrats :beers:

**Comment by MoOx** [comment]
me & @kud use online version, pretty nice & fast (as soon as content cached)

**Comment by armandabric** [comment]
If the online vesion is fast. Maybe we could re-think about using an external API as image provider (no more limitation)

**Comment by MoOx** [comment]
I'm already working on that using flickr api
https://github.com/putaindecode/tab/issues/7#issuecomment-58321532
