### ISSUE TITLE
Add a speed-dial feature

### ISSUE THREAD

**Issue by madx** [MoOx/tab#18]
Should we implement this? I think it _should not_ mimic Firefox'/Chrome's one. 

Only three or four small user-definable thumbnails or icons should be enough for everyone.

**Comment by armandabric** [comment]
:-1:

**Comment by madx** [comment]
Just to be clear, this is what I was thinking of:

![screenshot](http://drop.madx.me/nxl8y28tqiirvubfh9z43371cw40865.png)

**Comment by armandabric** [comment]
Personally I find great this project because it replace perfectly the empty `about:blank` page (and because the picture are nice). 

I do not want complex things in my new tab. And if I want shortcut to a website I use the bookmark or an dedicated plug-in.

**Comment by kud** [comment]
+1 for @Spy-Seth comment.

**Comment by madx** [comment]
I completely agree with you guys and I think this might no be enabled by default, but it would be a nice feature for some people (the ones that use about:newtab and not about:blank as default for example)

**Comment by magsout** [comment]
+1 @madx

**Comment by MoOx** [comment]
-1 for this. 
But
We should definitly make a way to extend page behavior via custom script.
Meanwhile you can make your own user script/style ;)

https://github.com/putaindecode/pretty-new-tab/issues/22

**Comment by kud** [comment]
It's a stupid comment but I like the icons and the "bubble".
