### ISSUE TITLE
Black screen on Safari

### ISSUE THREAD

**Issue by jbleuzen** [MoOx/tab#25]
On Safari 7.0.6, when I open a PretyNewTab then change my tab, and reselect the new tab, I get a black screen. 
No more animations and reload button don't work.

**Comment by kud** [comment]
I don't understand the scenario.

**Comment by jbleuzen** [comment]
With Safari : 
1 - Open a PrettyNewTab
2 - Switch to another tab (to copy a URL for instance)
3 - Switch back to previously opened tab => Black screen for me...

**Comment by MoOx** [comment]
I cant reproduce on Safari 8.
Any clue in console ?

**Comment by MoOx** [comment]
Ok I found something. Loosing focus is probably messing with some animationEnd or something.

**Comment by jbleuzen** [comment]
Nothing in console.

**Comment by MoOx** [comment]
Should be ok. Please confirm ;)

**Comment by jbleuzen** [comment]
It's ok for me now :)
Thanks !
