### ISSUE TITLE
Semi-transparent square in the top right corner

### ISSUE THREAD

**Issue by wakooka** [MoOx/tab#26]
Open http://putaindecode.io/pretty-new-tab/ in Chrome 37, Windows 7
This happens:
![screenshot](https://cloud.githubusercontent.com/assets/1606624/4505399/e1773106-4af3-11e4-984e-58180621a33a.jpg)

**Switching tab and going back to pretty-new-tab fixes it** :/
I haven't found out why yet, still looking into it.

**Comment by kud** [comment]
Weird. Chrome bug?

**Comment by wakooka** [comment]
I'd guess so...

**Comment by wakooka** [comment]
Resizing the window fixes it as well.

**Comment by MoOx** [comment]
Can you try to disable some weird css rules on the background container please ?
Can't reproduce on Chrome nor anything on OS X.

**Comment by wakooka** [comment]
Even weirder, I can't replicate the issue, when I open the file locally. The repo is up to date, though.
The only way for me to debug, is from Chrome dev tools, on the live website.
I believe this is causing it

```
.PrettyNewTab body,
.PrettyNewTab a {
    color: #fff;
    text-shadow:
      0 0 0.2rem rgba(0,0,0,.8),
      0 0.05rem 0.4rem rgba(0,0,0,.5),
      0 -0.05rem 0.4rem rgba(0,0,0,.5),
      0.05rem 0 0.4rem rgba(0,0,0,.5),
      -0.05rem 0 0.4rem rgba(0,0,0,.5)
    ;
  }
```

The square disapears when I uncheck the `text-shadow` property.
_I love you too Chrome_

**Comment by wakooka** [comment]
@MoOx Disabling css rules on the background container doesn't fix it.

**Comment by MoOx** [comment]
what about adding the backface visibility trick on the body, a rule ?

**Comment by wakooka** [comment]
No, it doesn't change anything, it must be a `text-shadow` rendering issue.

**Comment by wakooka** [comment]
I can't replicate it  on my laptop, chrome 37 windows 8.

**Comment by wakooka** [comment]
Random chrome bug, the square doesn't appear everytime, and I can't figure out why.
I'm closing the issue.

**Comment by kud** [comment]
:+1:
